apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: tomcats.tomcatoperator.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: tomcatoperator.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                version:
                  type: integer
                replicas:
                  type: integer
            status:
              type: object
              properties:
                readyReplicas:
                  type: integer
          required: [spec]
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: tomcats
    # singular name to be used as an alias on the CLI and for display
    singular: tomcat
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Tomcat
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - tc
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: webapps.tomcatoperator.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: tomcatoperator.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tomcat:
                  type: string
                url:
                  type: string
                contextPath:
                  type: string
            status:
              type: object
              properties:
                deployedArtifact:
                  type: string
                deploymentStatus:
                  type: array
                  items:
                    type: string
          required: [spec]
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: webapps
    # singular name to be used as an alias on the CLI and for display
    singular: webapp
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Webapp