apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: schemas.mysql.sample.javaoperatorsdk
spec:
  group: mysql.sample.javaoperatorsdk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - encoding
              properties:
                encoding:
                  type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: schemas
    singular: schema
    kind: MySQLSchema

